
import { Check, Bot, Zap, Database, Cog, Shield, Globe, Palette, UserCog } from 'lucide-react';

export const pricingData = {
  'reel-editing': {
    title: 'Video Editing Packages',
    key: 'reel-editing',
    description: 'Choose your edit style — crafted to match your vibe.',
    tiers: [
      {
        name: "Candy Style Edit",
        price: "₹700 – ₹2,000",
        features: [
          "Soft pastel color grading",
          "Dreamy transitions & beat sync",
          "Up to 45 sec (1080p export)",
          "1 free revision",
        ],
        delivery: "1-2 days depends on the complexity",
        addOns: [
          "Extra 10 sec @ ₹150",
          "Express Delivery +₹300",
          "Custom thumbnail @ ₹150",
        ],
        popular: false,
        color: "pink",
        buttonText: 'Select Plan',
      },
      {
        name: "Slo-Mo / Velocity Edit",
        price: "₹1,000 – ₹2,800",
        features: [
          "Smooth slow motion (Twixtor-style)",
          "Beat-perfect velocity transitions",
          "Emotional color tone",
          "1–2 revisions",
        ],
        delivery: "1-2 days depends on the complexity",
        addOns: [
            "Extra 10 sec @ ₹200",
            "Express Delivery +₹400",
            "Custom thumbnail @ ₹150",
        ],
        popular: true,
        color: "purple",
        buttonText: 'Select Plan',
      },
      {
        name: "Glitch & Sync Edit",
        price: "₹900 – ₹2,500",
        features: [
          "Advanced beat sync effects",
          "Glitch overlays & motion text",
          "Perfect for dance or anime",
          "2 revisions",
        ],
        delivery: "2-3 days",
        addOns: [
          "Extra 10 sec @ ₹200",
          "Express Delivery +₹500",
          "Custom thumbnail @ ₹150",
        ],
        popular: false,
        color: "green",
        buttonText: 'Select Plan',
      },
      {
        name: "Trendy Reel Edit",
        price: "₹500 – ₹1,800",
        features: [
          "Trend audio & captions",
          "Modern transitions",
          "Optimized for Instagram Reels",
          "1 revision",
        ],
        delivery: "2 Days",
        addOns: [
          "Extra 10 sec @ ₹100",
          "Express Delivery +₹300",
          "Custom thumbnail @ ₹150",
        ],
        popular: false,
        color: "yellow",
        buttonText: 'Select Plan',
      },
    ]
  },
  'ai-chatbot': {
    title: 'AI Chatbot',
    key: 'ai-chatbot',
    description: 'Automate your customer interactions with intelligent, custom-built chatbots.',
    tiers: [
      {
        name: 'FAQ/Support Bot',
        price: '₹8,000',
        features: [
          'Handles FAQs',
          'WhatsApp/Telegram Integration',
          'Deployed on chosen platform',
          '1 Month Free Support',
        ],
        details: ['Optional: Maintenance +₹2,000/month'],
        buttonText: 'Select Plan',
      },
      {
        name: 'Booking Bot',
        price: '₹15,000',
        popular: true,
        features: [
          'Order/Booking via Chat',
          'Google Sheet/Airtable Integration',
          'Owner Notifications',
          'Supports WhatsApp, Website, Messenger',
          '1 Month Free Support',
        ],
        details: ['Optional: Maintenance +₹3,500/month'],
        buttonText: 'Select Plan',
      },
      {
        name: 'GPT-Powered Bot',
        price: '₹25,000',
        features: [
          'Smart, Human-like Replies',
          'Uses OpenAI Credits (*not included in price*)',
          'Advanced Customization (intents, flows)',
          'Deployed on Website/WhatsApp/Telegram',
          '1 Month Free Support',
        ],
        details: ['Optional: Maintenance +₹5,000/month'],
        buttonText: 'Select Plan',
      },
    ],
  },
  'web-development': {
    title: 'Web Development',
    key: 'web-development',
    description: 'Flexible pricing for Next.js web development, designed to scale with your needs.',
    tiers: [
        {
            name: 'Basic Web Development',
            description: "Perfect for Small Businesses & Personal Sites",
            price: '₹20,000',
            priceSubtitle: 'Starting at',
            features: [
                { icon: Check, text: '1-3 Page Website' },
                { icon: Zap, text: 'Next.js Framework' },
                { icon: Database, text: 'Basic CMS Integration' },
                { icon: Check, text: '1 Month Support' },
            ],
            buttonText: 'Start Small',
            size: 'small',
        },
        {
            name: 'Intermediate Web Development',
            description: "Best for Growing Startups",
            price: '₹75,000',
            priceSubtitle: 'Starting at',
            popular: true,
            features: [
                { icon: Check, text: 'Up to 6 Page Website' },
                { icon: Zap, text: 'Next.js Framework' },
                { icon: Database, text: 'Advanced CMS' },
                { icon: Cog, text: 'Simple API Integrations' },
                { icon: Check, text: '2 Months Support' },
            ],
            buttonText: 'Grow Your Business',
            size: 'medium',
        },
        {
            name: 'Enterprise Web Development',
            description: "Custom Solutions for Enterprises",
            price: '₹1,50,000+',
            priceSubtitle: 'Starting at',
            priceSubDescription: 'Custom Pricing Available',
            features: [
                { icon: Check, text: '10+ Page Application' },
                { icon: Zap, text: 'Performance Optimization' },
                { icon: Shield, text: 'Advanced Security Setup' },
                { icon: Bot, text: 'AI Feature Integration' },
                { icon: Globe, text: 'Multi-language Support' },
                { icon: Palette, text: 'UI/UX Premium Design' },
                { icon: UserCog, text: 'Custom Admin Dashboard' },
                { icon: Cog, text: 'Custom Integrations' },
                { icon: Check, text: '3+ Months Support' },
            ],
            buttonText: 'Build Enterprise Solutions',
            size: 'large',
        },
    ]
  },
};
